language: cpp

deploy:
  provider: releases
  api_key:
    secure: UuLzE9QGUbX55KgSSfqSzGFWh9wsP82SnU7ZpnnnKKR8mmlEEaBULHexrPBcWfqveQtriGJyjh8Wq9h4Cr2yndbEI9B0JDev2rtnBuCpjoHLBEC1hT+/3UheElHLG/minwNHt6K+uukX6eHTSprrW6H6pE6Qa6Q39NnzT25Mvol+vc1/qdI5oEed39xoaSuno57dJ9dhgKKja5aMNBNQ0XAoVlafeY5byPs3fMUfhXTMP2webHF23PUsFXpuE28Yfp7gi6VlUdgpb4vxAI7xOBswfuftxE3lB+o7tIelzcOmWv0nGVPZ+Mo+XgyR4uba9OXz4tReOpC4uDyYXLHGMdX+qtjxfjj//crDZJrqjkEphRxesiNLb7V827W+VTN8RCsdqh3WAwfEiWFjTYDIPMgo9Ky/DBq5OCwIBwzUY9FTT+Nsp9C14bkZ3INWBdJh4Y1UdcRPFascYM4oq60P7M49ql2ze8Jr62e8jh6WNQJWbmcsnboit4VubPkAxUtqTD/cOUYtD7TDxqZdFECIEDtzhlWZlBqhQCgAF8IZ7HRt5+QY8t37uw+XcFWkzS9AO1HeTtQ23v9tAGx2eBymHTYub8w7avYfxx8Jv7vjIPiH1HUBCCBc1teUcQzSniyF3u1XLUrTJctTbvnOjkTAYBnguux67YeuvDgkc+tZpNw=
  file_glob: true
  file: prebuilds/*
  skip_cleanup: true
  on:
    tags: true
    repo: tortank-team/libtorrent-native

matrix:
  fast_finish: true
  include:
  - env: NODE_VERSION=6
    os: linux
  - env: NODE_VERSION=6
    os: osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

cache:
  directories:
  - "$HOME/boost"
  - "$HOME/libtorrent"
  - "$HOME/openssl"

install:
- export MACOSX_DEPLOYMENT_TARGET=10.9
- source scripts/install-node.sh $NODE_VERSION
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then scripts/install-boost.sh; fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then scripts/install-openssl.sh; fi
- scripts/install-libtorrent.sh

script:
- export CPATH=$CPATH:$HOME/boost/include
- export CPATH=$CPATH:$HOME/openssl/include
- export CPATH=$CPATH:$HOME/libtorrent/include
- export LIBRARY_PATH=$LIBRARY_PATH:$HOME/boost/lib
- export LIBRARY_PATH=$LIBRARY_PATH:$HOME/openssl/lib
- export LIBRARY_PATH=$LIBRARY_PATH:$HOME/libtorrent/lib
- scripts/build-travis.sh
